// LOCALHOST ### GET http://localhost:8080/contacts ### GET http://localhost:8080/contacts/663ac24aa07695e6c10aa437 ### GET http://localhost:8080/contacts/663ac2d8a07695e6c10aa438 ### GET http://localhost:8080/contacts/663ac321a07695e6c10aa439


//PRODUCTION ### GET https://cse-341-3gsy.onrender.com/contacts  ### GET https://cse-341-3gsy.onrender.com/contacts/663ac24aa07695e6c10aa437  ### GET https://cse-341-3gsy.onrender.com/contacts/663ac2d8a07695e6c10aa438  ### GET https://cse-341-3gsy.onrender.com/contacts/663ac321a07695e6c10aa439